### ISSUE TITLE
Fields with a null value are not shown

### ISSUE THREAD

**Issue by dcaravana** [jiyinyiyong/compact-json#2]
I need to show them, it's probably only a matter of adding `null` to the support_types:

```
support_types = ["number", "string", "array", "object", "null"]
```

Thanks for this tiny little jewel!

**Comment by jiyinyiyong** [comment]
Updated, please check.

**Comment by dcaravana** [comment]
Apart from this error:

`sh: node-dev: command not found`

all is fine!

A secondary issue is that I had some difficulty in understanding how to generate the .js file (I use it in a browser through Bower), then I've found it's a matter of running `./node_modules/.bin/gulp coffee`.

Finally `npm test` is not working, not sure how to proceed here since the corresponding command is `node test.coffee` so I'm supposing I ignore how to make it run.

After some research, I see you're most probably developing using https://github.com/fgnass/node-dev - is that correct?

**Comment by jiyinyiyong** [comment]
Yes it's written in CoffeeScript and code is generated with `gulp-coffee` and run with `coffee` command. 

And yes I used `node-dev` and it supports calling `coffee` for me.

The package is developed long time ago and things changed a lot. I would suggest using `npm` to manage dependencies.

**Comment by dcaravana** [comment]
All fine but all this should go into package.json in the proper places, else running your project requires guesswork which translates into making impossible to run/test it in an automated fashion.

Using `npm` does not fix the issues detailed above.

**Comment by tiye** [comment]
I just pushed some update.

This package is not well maintained. Inside a browser `JSON.stringify(data, null, 2)` is useful to small data, and for the larger we would need a real JSON viewer. You would probably prefer yaml of cson to format JSON if it's not in a browser.

**Comment by dcaravana** [comment]
Thank you for the changes and for your suggestions.

I know exactly what I need, and your project is exactly what I need as YAML and CSON are slightly less readable by (non-dev) humans - keep it running!

I see you've also removed `bower.json` file - does this mean that you're going to end support for bower?

**Comment by tiye** [comment]
Yes. Bower itself is lack for maintenance and I'm don't have time for this package too:
https://github.com/bower/bower/#bower---a-package-manager-for-the-web

> Bower needs resources for its maintenance. Please fill this form if you think you can help.
